# BridgeAPI filter for mitmproxy (https://www.mitmproxy.org/)
# Copyright 2026 Akretion France (https://www.akretion.com/)
# @author: Alexis de Lattre <alexis.delattre@akretion.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Command to install: sudo apt install mitmproxy

# Command to start:
# mitmdump -s bridgeapi_filter.py --set config=/etc/bridgeapi_filter.conf --set connection_strategy=lazy --mode reverse:https://api.bridgeapi.io --listen-port 8442

# Generate the Fernet symetric encryption key to be stored in the config file:
# from cryptography.fernet import Fernet
# print(Fernet.generate_key().decode('utf-8'))

# Sample config file /etc/bridgeapi_filter.conf:
# [config]
# encryption_key = <key generated by the python code above>
# min_odoo_secret_chars = 75
#
# [bridge_api]
# client_id = sandbox_id_9OQUJDLKSQJDLKSQJDLKSQD_NOT_TRUE
# secret = sandbox_secret_jdmlsqjfldsjOUO898DSQYsqndkjnsqk_SAMPLE
#
# [odoo]
# odoo_bridge_id-akretion-DSHQS8Q9798hdkjsqld = odoo_bridge_secret-akretion-DUONQUDO9SYdqdyfiuspa79879diuqyziuhdHUIGydsqyudtsqu
# odoo_bridge_id-projet-UDISQdysqoiuyfdsfiudsf = odoo_bridge_secret-projet-LJDLSQDIUSQDSQezdyusqdsqiuyfdsiyfIOUDSQOIDsqiud


from mitmproxy import http, ctx
import configparser
from cryptography.fernet import Fernet
import json
import os


class BridgeApiFilter:
    def __init__(self):
        self.config_path = None
        self.bridgeapi_client_id = None
        self.bridgeapi_secret = None
        self.odoo_client2secret = {}
        self.cipher = None
        self.min_odoo_secret_chars = None
        self.allowed_path2methods = {
            '/v3/aggregation/authorization/token': ['POST'],
            '/v3/aggregation/connect-sessions': ['POST'],
            '/v3/aggregation/users': ['POST', 'DELETE'],
            '/v3/aggregation/items': ['GET'],
            '/v3/aggregation/transactions': ['GET'],
            '/v3/aggregation/accounts': ['GET'],
            '/v3/providers': ['GET'],
            }

    # define the option on the command line
    def load(self, loader):
        loader.add_option(
            name="config", typespec=str, default="/etc/bridgeapi_filter.conf",
            help="Path to the configuration file.",
        )

    # load config file
    def configure(self, updated):
        if "config" in updated:
            config_path = ctx.options.config
            ctx.log.info(f"Config file: {config_path}")
            if not os.path.exists(config_path):
                ctx.log.error(f"Config file {config_path} doesn't exist")
                return
            try:
                config = configparser.ConfigParser()
                config.optionxform = lambda option: option
                config.read(config_path)
                self.bridgeapi_client_id = config['bridge_api']['client_id']
                self.bridgeapi_secret = config['bridge_api']['secret']
                if 'min_odoo_secret_chars' in config['config']:
                    try:
                        self.min_odoo_secret_chars = int(config['config']['min_odoo_secret_chars'])
                        ctx.log.debug(f"Min length for odoo secrets: {self.min_odoo_secret_chars}")
                    except Exception as e:
                        ctx.log.error(
                            f"Config param min_odoo_secret_chars is not an integer. "
                            f"Error: {str(e)}")
                odoo_client2secret = {}
                for odoo_client_id in config['odoo']:
                    odoo_secret = config['odoo'][odoo_client_id]
                    if self.min_odoo_secret_chars:
                        if len(odoo_secret) >= self.min_odoo_secret_chars:
                            odoo_client2secret[odoo_client_id] = odoo_secret
                            ctx.log.info(
                                f"Credentials for Odoo client ID '{odoo_client_id}' loaded")
                        else:
                            ctx.log.error(
                                f"Secret for Odoo client ID {odoo_client_id} only has "
                                f"{len(odoo_secret)} chars. "
                                f"Minimum is {self.min_odoo_secret_chars}")
                self.odoo_client2secret = odoo_client2secret
                encryption_key_str = config['config']['encryption_key']
                encryption_key_bin = encryption_key_str.encode('utf-8')
                self.cipher = Fernet(encryption_key_bin)
                ctx.log.info(f"Config loaded from {config_path}")
            except Exception as e:
                ctx.log.error(f"Failed to load config from {config_path}: {str(e)}")

    def request(self, flow: http.HTTPFlow) -> None:
        if (
                not self.bridgeapi_client_id
                or not self.bridgeapi_secret
                or not self.odoo_client2secret
                or not self.cipher):
            return
        path = flow.request.path.split('?')[0]
        method = flow.request.method
        if method == "DELETE":
            path_to_check = '/'.join(path.split('/')[:-1])
        else:
            path_to_check = path
        if (
                path_to_check in self.allowed_path2methods and
                method in self.allowed_path2methods[path_to_check]):
            ctx.log.info(f'{method} on {path} is allowed')
        else:
            flow.response = http.Response.make(
                403,
                f"BridgeAPI proxy: {method} on path {path} is not allowed.",
                {"Content-Type": "text/plain"}
            )
            return
        if path == "/v3/aggregation/authorization/token":
            json_dict = None
            try:
                json_dict = json.loads(flow.request.get_content())
            except json.JSONDecodeError:
                ctx.log.warn("Invalid JSON in request to get a token. It should never happen.")
            if not json_dict:
                flow.response = http.Response.make(
                    403,
                    f"BridgeAPI proxy: {method} on path {path} doesn't "
                    f"contain a valid JSON -> rejected.",
                    {"Content-Type": "text/plain"}
                )
            elif "external_user_id" in json_dict:
                flow.response = http.Response.make(
                    403,
                    f"BridgeAPI proxy: {method} on path {path} contains a key "
                    f"'external_user_id' is JSON -> rejected.",
                    {"Content-Type": "text/plain"}
                )
            elif "user_uuid" in json_dict:
                if json_dict['user_uuid'] and isinstance(json_dict['user_uuid'], str):
                    uuid_bytes = json_dict['user_uuid'].encode('utf-8')
                    encrypted_uuid_bytes = self.cipher.decrypt(uuid_bytes)
                    encrypted_uuid_str = encrypted_uuid_bytes.decode('utf-8')
                    new_json_dict = {"user_uuid": encrypted_uuid_str}
                    flow.request.set_content(json.dumps(new_json_dict).encode('utf-8'))
                    ctx.log.info(f'{method} on {path}: user_uuid has been encrypted')
                else:
                    flow.response = http.Response.make(
                        403,
                        f"BridgeAPI proxy: {method} on path {path} contains a JSON "
                        f"with key 'user_uuid' without value or a value which "
                        f"is not a string -> rejected.",
                        {"Content-Type": "text/plain"}
                    )
        elif method == "DELETE" and path_to_check == "/v3/aggregation/users":
            uuid_str = path.split('/')[-1]
            uuid_bytes = uuid_str.encode('utf-8')
            encrypted_uuid_bytes = self.cipher.decrypt(uuid_bytes)
            encrypted_uuid_str = encrypted_uuid_bytes.decode('utf-8')
            new_path = f"/v3/aggregation/users/{encrypted_uuid_str}"
            flow.request.path = new_path
            ctx.log.info(f"{method} on {path} changed to {new_path} to encrypt the UUID")

        odoo_clientid = flow.request.headers.get('Client-ID')
        odoo_secret = flow.request.headers.get('Client-Secret')
        if (
                odoo_clientid and
                odoo_secret and
                odoo_clientid in self.odoo_client2secret and
                odoo_secret == self.odoo_client2secret[odoo_clientid]):
            ctx.log.info(
                f"Incoming request with Odoo client ID '{odoo_clientid}' and good "
                f"secret. Replacing with Bridge credentials.")
            flow.request.headers["Client-ID"] = self.bridgeapi_client_id
            flow.request.headers["Client-Secret"] = self.bridgeapi_secret
        else:
            ctx.log.warn(f"Bad secret for ClientID '{odoo_clientid}'")

            flow.response = http.Response.make(
                403,
                b"BridgeAPI proxy: missing or invalid credentials.",
                {"Content-Type": "text/plain"}
            )

    # Encrypt UUID in answer to create user API
    def response(self, flow: http.HTTPFlow) -> None:
        if not self.cipher:
            return
        path = flow.request.path.split('?')[0]
        if path == "/v3/aggregation/users":
            json_dict = None
            try:
                json_dict = json.loads(flow.response.get_content())
            except json.JSONDecodeError:
                ctx.log.warn("Invalid JSON in answer to user creation. It should never happen.")
            if json_dict and json_dict.get('uuid'):
                uuid_str = json_dict['uuid']
                if isinstance(uuid_str, str):
                    uuid_bytes = uuid_str.encode('utf-8')
                    uuid_encrypted_bytes = self.cipher.encrypt(uuid_bytes)
                    uuid_encrypted_str = uuid_encrypted_bytes.decode('utf-8')
                    json_dict['uuid'] = uuid_encrypted_str
                    flow.response.set_content(json.dumps(json_dict).encode("utf-8"))
                    ctx.log.info("In answer to user creation, the uuid has been encrypted.")
                else:
                    ctx.log.warn(
                        "In answer to user creation, key uuid is not a str. "
                        "It should never happen.")
            else:
                ctx.log.warn(
                    "In answer to user creation, the json is empty or the uuid "
                    "key is empty. It should never happen.")


addons = [BridgeApiFilter()]
