services:
  ais:
    restart: always
    image: mitmproxy/mitmproxy:latest
    ports:
      - "8080:8080"
    volumes:
      - ./bridgeapi_filter.py:/opt/bridgeapi_filter.py
      - ./config:/opt/config
    command: mitmdump -s /opt/bridgeapi_filter.py --set config=/opt/config/bridgeapi_filter.conf --mode reverse:https://api.bridgeapi.io --listen-port 8080
